server:
  port: 5003
spring:
  application:
    name: serviceC
  datasource:
    username: root
    password: xxxx
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.6.21:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath*:mybatis/mapper/*Mapper.xml


tx-lcn:
  client:
    manager-address: 127.0.0.1:8070